-- Supabase schema for the GitHub Pages imageboard starter.
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.boards (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]{1,16}$'),
  name text not null,
  description text,
  is_public boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.threads (
  id bigint generated by default as identity primary key,
  board_id bigint not null references public.boards(id) on delete cascade,
  subject text check (subject is null or char_length(subject) <= 120),
  comment text not null check (char_length(comment) between 1 and 5000),
  poster_id uuid not null,
  image_path text,
  image_url text,
  reply_count integer not null default 1,
  created_at timestamptz not null default now(),
  bumped_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.threads(id) on delete cascade,
  comment text not null check (char_length(comment) between 1 and 5000),
  poster_id uuid not null,
  image_path text,
  image_url text,
  created_at timestamptz not null default now()
);

create index if not exists threads_board_bumped_idx
  on public.threads(board_id, bumped_at desc);

create index if not exists posts_thread_created_idx
  on public.posts(thread_id, created_at asc);

-- Keep reply_count and bumped_at synchronized automatically.
create or replace function public.bump_thread_after_reply()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.threads
  set reply_count = reply_count + 1,
      bumped_at = now()
  where id = new.thread_id;

  return new;
end;
$$;

drop trigger if exists posts_bump_thread on public.posts;

create trigger posts_bump_thread
after insert on public.posts
for each row
execute function public.bump_thread_after_reply();

-- Seed boards. Safe to re-run.
insert into public.boards (slug, name, description)
values
  ('b', 'Random', 'Anything goes within the site rules.'),
  ('g', 'Technology', 'Computers, software and technology.'),
  ('art', 'Artwork', 'Drawings, photography and other artwork.')
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description;

-- Enable RLS.
alter table public.boards enable row level security;
alter table public.threads enable row level security;
alter table public.posts enable row level security;

-- Public board discovery.
drop policy if exists "public can read public boards" on public.boards;
create policy "public can read public boards"
on public.boards
for select
to anon, authenticated
using (is_public = true);

-- Public thread reading.
drop policy if exists "public can read threads" on public.threads;
create policy "public can read threads"
on public.threads
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.boards b
    where b.id = threads.board_id
      and b.is_public = true
  )
);

-- Anonymous thread creation.
drop policy if exists "public can create threads" on public.threads;
create policy "public can create threads"
on public.threads
for insert
to anon, authenticated
with check (
  exists (
    select 1
    from public.boards b
    where b.id = threads.board_id
      and b.is_public = true
  )
);

-- Public reply reading.
drop policy if exists "public can read posts" on public.posts;
create policy "public can read posts"
on public.posts
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.threads t
    join public.boards b on b.id = t.board_id
    where t.id = posts.thread_id
      and b.is_public = true
  )
);

-- Anonymous reply creation.
drop policy if exists "public can create posts" on public.posts;
create policy "public can create posts"
on public.posts
for insert
to anon, authenticated
with check (
  exists (
    select 1
    from public.threads t
    join public.boards b on b.id = t.board_id
    where t.id = posts.thread_id
      and b.is_public = true
  )
);

-- Storage bucket for public images.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'images',
  'images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/gif', 'image/webp']
)
on conflict (id) do update
set public = true,
    file_size_limit = 5242880,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/gif', 'image/webp'];

-- Public image downloads are handled by the public bucket.
drop policy if exists "public can view imageboard images" on storage.objects;
create policy "public can view imageboard images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'images');

-- Allow anonymous clients to upload images into the bucket.
-- The application creates UUID filenames and validates type/size client-side;
-- the bucket itself also enforces type and size limits.
drop policy if exists "public can upload imageboard images" on storage.objects;
create policy "public can upload imageboard images"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id = 'images'
  and (storage.extension(name) in ('jpg', 'jpeg', 'png', 'gif', 'webp'))
);

-- There are deliberately no public update/delete policies.
-- Add moderator-only policies later if you implement moderation.
